baseurl: "/"
# languageCode: "en-us"
# defaultContentLanguage: "en"
languageCode: "zh-cn"
defaultContentLanguage: "zh"
title: "BIO-SPRING"
theme: "hugo-prose"
googleAnalytics: "G-77M8KZTCMR"
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

# 不检查 hugo 版本
hugo_version: ""

# Use pagination.pagerSize
pagination:
  pagerSize: 10
  
# Use .Site.Config.Services.Disqus.Shortname
Services:
  Disqus:
    Shortname: "bio-spring"


permalinks:
  post: "/post/:year/:month/:day/:slug/"

outputs:
  home: [html, json]

# some menu items were added via the `menu` option in YAML in posts
menu:
  header:
    - name: Home
      url: "/"
      weight: 1
    - name: Blog
      url: "/post/"
      weight: 3
    - name: Work
      url: "/work/"
      weight: 6
    - name: Search
      weight: 50
      url: "#"
      identifier: menu-search
  footer:
    - name: Contact
      url: "/404.html"
      weight: 1
    - name: Categories
      url: "/categories/"
      weight: 2
      pre: "optional"
    - name: Tags
      url: "/tags/"
      weight: 3
      pre: "optional"
    - name: Suggest an edit
      url: "#"
      weight: 4
      identifier: "menu-edit"
    - name: Back to top
      url: "#"

params:
  homePosts: 6
  # max number of categories displayed in article list
  numCategories: 3
  fuseVersion: 6.6.2
  mainSections: ["post"]
  editLink: "https://github.com/gaospecial/bio-spring/edit/master/content/"
  authorDelimiter: " / "
  stickyMenu: true
  description: >
    Chun-Hui Gao's personal website built through Hugo and blogdown with the hugo-prose theme.
  footer: >
    &copy; [Bio-Spring](https://bio-spring.top) 2006 -- 2026 [豫ICP备2021003240号](https://beian.miit.gov.cn)
  license: >
    Text and figures are licensed under [Creative Commons Attribution CC BY
    4.0](https://creativecommons.org/licenses/by/4.0/). The source code is
    licensed under MIT. The full source is available at
    https://github.com/yihui/hugo-prose.
  disable_path: ["categories", "tags"]


markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
